### ISSUE TITLE
Harden parsing of invalid programs

### ISSUE THREAD

**Issue by mpo-mjolner** [Open-Pectus/Open-Pectus#21]
- Add various fall-back grammar constructs
- Implement common errors in semantic analyzer
- On interpretation error, choose the relevant action (stop/hold/pause) and report the error

**Comment by nneskildsf** [comment]
The correct action on interpreter error is to do nothing by default. If the user wants a particular action, then it is possible to define a `Watch` or an `Alarm` which triggers off of the `Method Status` tag having value `Error`. Example:
```
Watch: Method Status = Error
    Pause
```

**Comment by mpo-mjolner** [comment]
Fixed in #437
