### ISSUE TITLE
Consider engine dispatcher retry strategy

### ISSUE THREAD

**Issue by jhk-mjolner** [Open-Pectus/Open-Pectus#240]
Currently, we have a health check against the aggregator, that tries to exit the application.
We might want to change that to use a retry strategy, or rely on the websocket library's implementation of same.
Also consider what should happen if the connection dies during a run. websocket library and Starlette's implementation might be the best option there.

Ask PO about whether engine should exit when it can't communicate with aggregator at startup, or whether we want a retry strategy.

related: #209

**Comment by mpo-mjolner** [comment]
Also related #261 and #324

**Comment by mpo-mjolner** [comment]
@nnsivll What do you think?
