### ISSUE TITLE
Implement OPCUA hardware

### ISSUE THREAD

**Issue by mpo-mjolner** [Open-Pectus/Open-Pectus#282]

**Comment by mpo-mjolner** [comment]
@nneskildsf Så er der en branch klar. Det er nok nødvendigt at du får sat et udviklingsmiljø op som beskrevet i https://github.com/Open-Pectus/Open-Pectus/blob/main/DEVELOPMENT.md

**Comment by nneskildsf** [comment]
Hi

I realized that we need the following functionality, and we didn't touch on it in our discussion yesterday.

When we start an engine then it should immediately write safe output values to the hardware endpoints. This is necessary to bring the hardware into a known state.
I think it would be sensible for this logic to be a part of the engine initialization which would trigger a write to all hardware endpoints. As such I will not implement this logic into the hardware-module itself.

What do you think?

**Comment by mpo-mjolner** [comment]
> Hi
> 
> I realized that we need the following functionality, and we didn't touch on it in our discussion yesterday.
> 
> When we start an engine then it should immediately write safe output values to the hardware endpoints. This is necessary to bring the hardware into a known state. I think it would be sensible for this logic to be a part of the engine initialization which would trigger a write to all hardware endpoints. As such I will not implement this logic into the hardware-module itself.
> 
> What do you think?

This makes good sense. I have create issue #286 for this feature.

**Comment by mpo-mjolner** [comment]
@nneskildsf The code looks very good. It is more involved than I thought, so I would like a talk about it. Go ahead and make a pull request if you're happy with it, then we can walk through it.
