### ISSUE TITLE
Handle interrupted_by_error flag

### ISSUE THREAD

**Issue by jhk-mjolner** [Open-Pectus/Open-Pectus#324]
set interrupted_by_error flag when engine is paused by an error.
- And reset when engine is started again
- publish that process units have changed when their state changes.

`engine_data.run_data.interrupted_by_error`

**Comment by jhk-mjolner** [comment]
https://github.com/Open-Pectus/Open-Pectus/issues/311

**Comment by mpo-mjolner** [comment]
Add similar interrupted_by_error to engine
Set this on error
In many tests, assert this flag is False

**Comment by mpo-mjolner** [comment]
This task is complete
