### ISSUE TITLE
Convenience function on UodCommandBuilder to use regex to parse argument

### ISSUE THREAD

**Issue by nneskildsf** [Open-Pectus/Open-Pectus#346]
`UodCommandBuilder` has a method`with_arg_parse_fn` which provides and interface to add a function to parse arguments.
I propose addition of a method `with_regex_arg_parse` which can be supplied with a regular expression.

Furthermore I propose that the parameters that are captured by the regex are assigned to `UodCommand` as a property e.g. `cmd.argument` such that parameters are accessible by name.
It is definitely also a good idea to keep track of the raw argument string so that it is also available as a property of the `UodCommand` object.

### Example:
Suppose a UOD requires a command to assign a value to a tag: `Assign area: 2.3 m2`.
Then I would like to register this command in the UOD like so:
```python
# Define command body
def assign_value(cmd: UodCommand, args: List[Any]) -> None:
    value = float(cmd.argument["value"]) # This is necessary because regex matches are str type.
    cmd.context.tags.get("Area").set_value(value)
    cmd.set_complete()

def create_uod() -> UnitOperationDefinitionBase:
    builder = UodBuilder()
    return (builder
        .with_instrument("Test")
        .with_tag(tags.ReadingTag("Area", "m2")
        .with_command(UodCommand.builder().with_name("Assign area").with_exec_fn(assign_value).with_regex_arg_parse(r"(?P<value>[0-9]+[.][0-9]*?|[.][0-9]+|[0-9]+) ?(?P<unit>m2)") # This regex forces the area to be non-negative
        .build()
    )
```

I hope you can help me implement this functionality :-).

Br Eskild

**Comment by mpo-mjolner** [comment]
This functionality fits well with #350 so it will be implemented there.
