### ISSUE TITLE
Fix process value units display

### ISSUE THREAD

**Issue by mpo-mjolner** [Open-Pectus/Open-Pectus#359]

**Comment by mpo-mjolner** [comment]
We should look into the display of units. This screenshot shows a 'null' units for time. In this case no unit should be shown. 

![Image](https://github.com/Open-Pectus/Open-Pectus/assets/122263767/bfc10a84-167b-456f-ab29-f4abd419b48b)

The data delivered at by `/api/process_unit/MIAWLT-1645-MPO_DemoUod/process_values` for `Category` and `Time` is:
```
  {
        "name": "Category",
        "value": "Rising",
        "value_unit": null,
        "value_type": "string",
        "commands": [],
        "direction": "input"
    },
    {
        "name": "Time",
        "value": 20.019849061965942,
        "value_unit": null,
        "value_type": "float",
        "commands": [],
        "direction": "input"
    },
```

We should probably also document this better in the backend source. E.g. it is not obvious whether `value_unit` should be the empty string or `None` for no unit.

**Comment by jhk-mjolner** [comment]
wrt. the documentation, I think `None` is more correct when there is no unit for a given value and will be easier to detect where relevant.
But both null and empty string will show up the same in the frontend now.
