### ISSUE TITLE
Take unit into account when command is parsed by RegexNumberWithUnit

### ISSUE THREAD

**Issue by nneskildsf** [Open-Pectus/Open-Pectus#362]
When an argument is parsed by `RegexNumberWithUnit` e.g. `RegexNumberWithUnit(units=['L', 'mL'])` then the float value `number` should be parsed to a `pint`-unit aware value.
Writing a `pint`-unit aware value to a tag e.g. with a specific unit e.g. `with_tag(tags.ReadingTag("Volume", "L"))`, `cmd.context.tags.get("Volume").set_value(number, time())` should implicitply attempt to do the conversion to the unit specified for the tag.

**Comment by mpo-mjolner** [comment]
This is more or less what should already happen. Have you seen indications that this is not working?

**Comment by nneskildsf** [comment]
Nope :-) I just wanted to be sure. Thanks!
