### ISSUE TITLE
Engine state sync is sometimes lost

### ISSUE THREAD

**Issue by mpo-mjolner** [Open-Pectus/Open-Pectus#364]
Sometimes the frontend and engine are not in sync regarding runstate, e.g. engine is in Running state and frontend thinks it is Stopped.

Investigate and fix this.

**Comment by mpo-mjolner** [comment]
* Document a repro
* Define a "full update" frontend message/message sequence
* Possibly fix by posting "full update" on engine connect

**Comment by jhk-mjolner** [comment]
With https://github.com/Open-Pectus/Open-Pectus/issues/379 done, this might not be an issue any more.
Let me know if it continues to be an issue.

**Comment by mpo-mjolner** [comment]
The issue is resolved with #379
