### ISSUE TITLE
Investigate Azure container options

### ISSUE THREAD

**Issue by mpo-mjolner** [Open-Pectus/Open-Pectus#48]
Github directly supports deployment to
- Azure Web App
- Azure Functions App.

Via third party Github Actions (Microsoft) deployment to Azure Container Instance is also supported (https://learn.microsoft.com/en-us/azure/container-instances/container-instances-github-action?tabs=userlevel)

See this for comparison between ACS and Azure web apps
- https://stackoverflow.com/questions/47232013/difference-between-azure-container-service-and-web-app-for-containers#47233235

See this for comparison between ACI and ACA
- https://serverfault.com/questions/1083358/difference-between-azure-container-instances-and-azure-container-apps

Broader MS comparison of Azure container based services
- https://learn.microsoft.com/en-us/azure/container-apps/compare-options
- From this, it appears Azure App Service and Azure Container Instance both suit our needs. 

As always, the Azure naming is ambigous and it is not immidiately clear whether Azure Web App and Azure App Service is the same thing. Looking into it, they are in fact the same thing (https://stackoverflow.com/questions/66460146/what-is-the-difference-between-azure-web-app-and-azure-app-service).

### The immidiate conclusion is:
- we can use Azure Web App/Azure App Service or ACI for hosting Aggregator
- Github supports deploying to both

**Comment by nneskildsf** [comment]
Hi. I will re-open this ticket because I think the scope is wider than Github and Azure possibilities. I think the scope should also include what is possible in the target enterprise system. I will report on this in the morning meetings when I have made progress.

**Comment by nneskildsf** [comment]
I have investigated the following:
1. Deployment to Azure Container Instance
2. Deployment to Azure Web App
3. Deployment to Azure Virtual Machine

I think option 1 is optimal for testing and development and that option 3 is optimal for production deployment.

Currently, an Azure Container Instance is running at http://github.openpectus.org/ for development purposes. A virtual machine on the closed enterprise network is also operational for "production" use.

Br Eskild
