### ISSUE TITLE
with_hardware_register method takes string input

### ISSUE THREAD

**Issue by nneskildsf** [Open-Pectus/Open-Pectus#480]
Hi

The `with_hardware_register` method takes the tag name and register direction as inputs, both of them as `str`. I would prefer if the register direction was instead specified using the `RegisterDirection` enum directly. This would help me avoid upper/lower-case errors and make it clear to the reader that it is not an "anything goes" string value.

Br Eskild

**Comment by mpo-mjolner** [comment]
Good point. Lately I've been changing some uses of enum to a Literal type instead. This gives the same type safety via pyright and but gives better hints in VS Code. Lets have a look at it.
