### ISSUE TITLE
Store data in docker volume

### ISSUE THREAD

**Issue by nneskildsf** [Open-Pectus/Open-Pectus#483]
Store persistent data in docker volume instead of locally on running docker instance.

Br Eskild

**Comment by mpo-mjolner** [comment]
Yes, that was the plan. A more cloud-native approach would be to use a DB engine and store data there (suggested to @nnsivll by a cloud architect). Both approaches work. IRRC, the argument was that backup of a DB server was more straightforward than of a docker volume.

**Comment by nneskildsf** [comment]
https://docs.docker.com/engine/storage/volumes/#syntax

**Comment by mpo-mjolner** [comment]
Fix with #560. Closing this issue.
